// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/prac_proj.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IvServiceClient is the client API for IvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IvServiceClient interface {
	Create_IV(ctx context.Context, in *IVStruct, opts ...grpc.CallOption) (*Response_IV, error)
}

type ivServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIvServiceClient(cc grpc.ClientConnInterface) IvServiceClient {
	return &ivServiceClient{cc}
}

func (c *ivServiceClient) Create_IV(ctx context.Context, in *IVStruct, opts ...grpc.CallOption) (*Response_IV, error) {
	out := new(Response_IV)
	err := c.cc.Invoke(ctx, "/prac_proj.Iv_service/create_IV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IvServiceServer is the server API for IvService service.
// All implementations must embed UnimplementedIvServiceServer
// for forward compatibility
type IvServiceServer interface {
	Create_IV(context.Context, *IVStruct) (*Response_IV, error)
	mustEmbedUnimplementedIvServiceServer()
}

// UnimplementedIvServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIvServiceServer struct {
}

func (UnimplementedIvServiceServer) Create_IV(context.Context, *IVStruct) (*Response_IV, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create_IV not implemented")
}
func (UnimplementedIvServiceServer) mustEmbedUnimplementedIvServiceServer() {}

// UnsafeIvServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IvServiceServer will
// result in compilation errors.
type UnsafeIvServiceServer interface {
	mustEmbedUnimplementedIvServiceServer()
}

func RegisterIvServiceServer(s grpc.ServiceRegistrar, srv IvServiceServer) {
	s.RegisterService(&IvService_ServiceDesc, srv)
}

func _IvService_Create_IV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IVStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IvServiceServer).Create_IV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prac_proj.Iv_service/create_IV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IvServiceServer).Create_IV(ctx, req.(*IVStruct))
	}
	return interceptor(ctx, in, info, handler)
}

// IvService_ServiceDesc is the grpc.ServiceDesc for IvService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IvService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prac_proj.Iv_service",
	HandlerType: (*IvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create_IV",
			Handler:    _IvService_Create_IV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/prac_proj.proto",
}
